"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import {
  fetchLiveSignals,
  fetchPerformanceSummary,
  formatHorizonOutcome,
  type PerformanceSummary,
  type PublicSignal
} from "@/lib/api/public-signals";
import {
  fetchPublicHistoricalValidationSummary,
  formatAccuracyPercent,
  type PublicHistoricalValidationResponse
} from "@/lib/api/historical-validation";
import { usePublishAssistantContext } from "@/lib/assistant/context";
import { borderRadius, spacing, surfaceGlowClassName, typography } from "@/lib/design-system";
import { isoDateInNewYork } from "@/lib/market-hours-et";
import { SUBHEADING_DAY_CADENCE, SUBHEADING_SWING_CADENCE } from "@/lib/mode-terminology";
import { useTheme } from "@/lib/theme-provider";

function outcomeLabel(outcome: PublicSignal["outcome"]): string {
  if (outcome === "correct") return "Price moved in signal direction";
  if (outcome === "incorrect") return "Price moved against signal direction";
  if (outcome === "neutral") return "Price drifted (no clear move)";
  return "Pending evaluation";
}

interface PerformanceTrackingContentProps {
  showHomeLink?: boolean;
}

export function PerformanceTrackingContent({ showHomeLink = false }: PerformanceTrackingContentProps) {
  const { colors } = useTheme();
  const [signals, setSignals] = useState<PublicSignal[]>([]);
  const [summary, setSummary] = useState<PerformanceSummary | null>(null);
  const [validation, setValidation] = useState<PublicHistoricalValidationResponse | null>(null);

  usePublishAssistantContext({ page: "dashboard/performance" });

  useEffect(() => {
    let active = true;
    const load = async () => {
      // Fetch in parallel — the historical validation mirror is its own endpoint, so
      // a slow / failing call there should not block the legacy performance summary or
      // the live signals table from rendering.
      const [s, p, v] = await Promise.all([
        fetchLiveSignals(),
        fetchPerformanceSummary(),
        fetchPublicHistoricalValidationSummary({ daysBack: 90, horizon: "1d" })
      ]);
      if (!active) return;
      setSignals(s);
      setSummary(p);
      setValidation(v);
    };
    void load();
    return () => {
      active = false;
    };
  }, []);

  const launchDate = summary?.launch_date ?? isoDateInNewYork();
  const resolvedCount = summary?.signals_evaluated ?? 0;
  const showTable = signals.length > 0;

  const metricCardStyle = {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: borderRadius.xl,
    padding: spacing[4]
  } as const;

  const bodyPanelStyle = {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: borderRadius.xl,
    padding: spacing[6]
  } as const;

  return (
    <div className="overflow-x-hidden" style={{ color: colors.text }}>
      {showHomeLink ? (
        <Link href="/" className="text-sm hover:underline" style={{ color: colors.accent }}>
          ← Back to home
        </Link>
      ) : null}
      <h1 className={`font-black ${showHomeLink ? "mt-5 text-4xl md:text-6xl" : "text-2xl md:text-3xl"}`}>
        Signal outcome tracking
      </h1>
      <p className={`max-w-4xl ${showHomeLink ? "mt-3 md:text-xl" : "mt-2 text-sm md:text-base"}`} style={{ color: colors.textMuted }}>
        Every signal generated by STOCVEST is tracked against subsequent market price movement. Directional accuracy reflects signal
        direction only — not trading returns. Individual results will vary based on entry timing, position size, and execution. Historical
        signal accuracy does not guarantee future results.
      </p>

      {/*
       * Mode Separation safety perimeter (assistant_prompts.py): "Never headline
       * a combined accuracy or result across Day and Swing." The legacy top row
       * carried a single "Directional Accuracy" card averaged across both
       * engines — removed. Per-mode accuracy now lives ONLY in the
       * PublicValidationSection below (Swing track / Day track), where each
       * engine reports its own number with its own context window.
       */}
      <section
        className={`grid grid-cols-1 gap-3 sm:grid-cols-2 ${showHomeLink ? "mt-8 lg:grid-cols-3" : "mt-6 lg:grid-cols-3"}`}
      >
        <div className={surfaceGlowClassName} style={metricCardStyle}>
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            Total Signals
          </p>
          <p className="mt-2 text-2xl font-bold">{summary?.total_signals_tracked ?? 0}</p>
        </div>
        <div className={surfaceGlowClassName} style={metricCardStyle}>
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            Signals Evaluated
          </p>
          <p className="mt-2 text-2xl font-bold">{resolvedCount}</p>
        </div>
        <div className={surfaceGlowClassName} style={metricCardStyle}>
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            Tracking Since
          </p>
          <p className="mt-2 text-2xl font-bold">{launchDate}</p>
          <p className="mt-1 text-[11px] leading-snug" style={{ color: colors.textMuted }}>
            US/Eastern market calendar
          </p>
        </div>
      </section>

      {resolvedCount > 0 ? (
        <p className="mt-4 text-sm" style={{ color: colors.textMuted }}>
          Based on {resolvedCount} resolved signal{resolvedCount === 1 ? "" : "s"} since launch (1d horizon). Per-engine
          accuracy is broken out in the Swing track and Day track cards below.
        </p>
      ) : null}

      {validation ? (
        <PublicValidationSection
          validation={validation}
          surfaceClass={surfaceGlowClassName}
          panelStyle={bodyPanelStyle}
          metricCardStyle={metricCardStyle}
          colors={colors}
          showHomeLink={showHomeLink}
        />
      ) : null}

      {!showTable ? (
        <section className={`${surfaceGlowClassName} ${showHomeLink ? "mt-8" : "mt-6"}`} style={bodyPanelStyle}>
          <h2 className="text-2xl font-bold">Tracking initialized</h2>
          <p className="mt-3 leading-relaxed" style={{ color: colors.textMuted }}>
            Performance metrics populate after first resolved setups. We launched on {launchDate} (US/Eastern). Every
            signal is evaluated for directional accuracy only — not dollar P&amp;L. Historical signal accuracy does not
            guarantee future results.
          </p>
          {showHomeLink ? (
            <Link
              href="/#live-signals"
              className="mt-5 inline-block rounded-md px-4 py-2 text-sm"
              style={{
                border: `1px solid ${colors.border}`,
                color: colors.accent
              }}
            >
              View Live Signals
            </Link>
          ) : null}
        </section>
      ) : (
        <section
          className={`overflow-x-auto overscroll-x-contain touch-pan-x ${surfaceGlowClassName} ${showHomeLink ? "mt-8" : "mt-6"}`}
          style={{
            background: colors.surface,
            border: `1px solid ${colors.border}`,
            borderRadius: borderRadius.xl,
            padding: spacing[3]
          }}
        >
          <table className="w-full min-w-[900px] text-sm" style={{ borderCollapse: "collapse", fontSize: typography.scale.sm }}>
            <thead>
              <tr className="text-left" style={{ borderBottom: `1px solid ${colors.border}`, color: colors.textMuted }}>
                <th className="px-4 py-3">Symbol</th>
                <th className="px-4 py-3">Direction</th>
                <th className="px-4 py-3">Signal Strength</th>
                <th className="px-4 py-3">Date and Time</th>
                <th className="px-4 py-3">1h</th>
                <th className="px-4 py-3">1d</th>
                <th className="px-4 py-3">Legacy</th>
              </tr>
            </thead>
            <tbody>
              {signals.map((row) => {
                const h1 = formatHorizonOutcome(row.outcome_1h);
                const h1d = formatHorizonOutcome(row.outcome_1d);
                return (
                  <tr key={row.signal_id ?? `${row.symbol}-${row.timestamp_iso}`} style={{ borderBottom: `1px solid ${colors.border}` }}>
                    <td className="px-4 py-3 font-semibold">{row.symbol}</td>
                    <td className="px-4 py-3 capitalize">{row.bias}</td>
                    <td className="px-4 py-3">{Math.round(row.signal_strength)}%</td>
                    <td className="px-4 py-3" style={{ color: colors.textMuted }}>
                      {new Date(row.timestamp_iso).toLocaleString()}
                    </td>
                    <td className="px-4 py-3" style={{ color: colors.textMuted }}>
                      {h1.label}
                    </td>
                    <td className="px-4 py-3" style={{ color: colors.textMuted }}>
                      {h1d.label}
                    </td>
                    <td className="px-4 py-3">{outcomeLabel(row.outcome)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>
      )}

      {/*
       * Phase 2c — Signal Validation Ledger link. The full stratified ledger
       * (decision state × regime × setup pattern × readiness × direction) is
       * a PERFORMANCE-page artifact, not a dashboard artifact: tracked
       * outcomes describe "did past signals work?", which is a performance
       * question and explicitly NOT shared market context. The link surface
       * lives here, in the logged-in Performance view, so it is one click
       * from the Signal Outcome table above.
       *
       * Rendered ONLY for logged-in users (`!showHomeLink`). The homepage
       * Performance mirror deliberately stops at the per-mode tracks above
       * — the stratified breakdown is gated behind login at the API layer
       * (Phase 3c-1) and on the UI layer here.
       */}
      {!showHomeLink ? (
        <section
          className={`${surfaceGlowClassName} mt-6`}
          style={bodyPanelStyle}
          data-testid="performance-validation-ledger-link"
        >
          <div className="flex flex-wrap items-baseline justify-between gap-2">
            <p
              style={{
                margin: 0,
                fontSize: 11,
                letterSpacing: "0.18em",
                textTransform: "uppercase",
                fontWeight: 700,
                color: colors.textMuted
              }}
            >
              Validation ledger · stratified outcomes
            </p>
            <Link
              href="/dashboard/signal-validation"
              className="hover:underline"
              style={{ fontSize: typography.scale.sm, color: colors.accent, fontWeight: 600 }}
              data-testid="performance-validation-ledger-link-anchor"
            >
              Open full ledger (Swing / Day) →
            </Link>
          </div>
          <p className="mt-2 text-sm" style={{ color: colors.textMuted, lineHeight: 1.5 }}>
            Detailed historical signal validation — broken out by decision state, regime, setup pattern, readiness band,
            and direction. Swing and Day tracks are kept structurally separate so accuracy in one engine never
            implies permission to act in the other (Mode Separation).
          </p>
          <p className="mt-1 text-xs" style={{ color: colors.textMuted, fontStyle: "italic" }}>
            Tracked outcomes only — not a brokerage account, not a recommendation. Past directional accuracy does not
            guarantee future results.
          </p>
        </section>
      ) : null}

      <section className={`${surfaceGlowClassName} ${showHomeLink ? "mt-8" : "mt-6"}`} style={bodyPanelStyle}>
        <h2 className="text-2xl font-bold">Our commitment to transparency</h2>
        <ul className="mt-3 list-disc space-y-1 pl-6" style={{ color: colors.textMuted }}>
          <li>We publish signal outcomes — not only directionally correct results</li>
          <li>Small sample sizes are shown with sample count</li>
          <li>Past signal accuracy does not guarantee future results</li>
          <li>Directional accuracy uses resolved 1d outcomes; correct ÷ (correct + incorrect), excluding neutral moves</li>
          <li>Moves within 0.1% are scored as neutral</li>
        </ul>
      </section>
    </div>
  );
}

export interface PublicValidationSectionProps {
  validation: PublicHistoricalValidationResponse;
  surfaceClass: string;
  panelStyle: { background: string; border: string; borderRadius: string; padding: string };
  metricCardStyle: { background: string; border: string; borderRadius: string; padding: string };
  colors: ReturnType<typeof useTheme>["colors"];
  showHomeLink?: boolean;
}

/**
 * Public mirror of D2 Historical Signal Validation — homepage `/performance` surface.
 *
 * Renders ONLY the `overall` + `by_mode` projection that the backend ships at
 * `GET /v1/signals/historical-validation/public-summary`. The full stratification grid
 * (decision state, regime, pattern, readiness, direction) lives behind the login on
 * `/dashboard/signal-validation` — the LOGGED-OUT golden rule from the assistant prompt
 * is "Explain the FRAMEWORK, not the DECISION", and that boundary is enforced both at
 * the API layer (Phase 3c-1 backend) and here at the rendering layer.
 */
export function PublicValidationSection({
  validation,
  surfaceClass,
  panelStyle,
  metricCardStyle,
  colors,
  showHomeLink
}: PublicValidationSectionProps) {
  // `overall` deliberately not destructured — Mode Separation rule forbids
  // surfacing a combined-engine headline on this page. The per-mode buckets
  // are the only metrics rendered.
  const { by_mode: byMode, rows_examined: rowsExamined } = validation.summary;
  const swing = byMode.swing;
  const day = byMode.day;

  return (
    <section className={`${surfaceClass} ${showHomeLink ? "mt-8" : "mt-6"}`} style={panelStyle}>
      <h2 className="text-2xl font-bold">Historical signal validation (last 90 days)</h2>
      <p className="mt-2 text-sm" style={{ color: colors.textMuted }}>
        Directional accuracy of real signals that STOCVEST emitted in the last 90 days, resolved against later prices.
        Neutrals (small drift moves) are excluded from the denominator. Nothing here is simulated and nothing here is a forecast.
      </p>

      {/*
       * Two cards only — Mode Separation rule "Statistics, hit-rates, and
       * outcomes must never be combined into a single headline number." The
       * legacy "Overall accuracy (1d)" card averaged swing and day signals
       * into one number — removed. Each engine now reports its own track
       * record on its own card, side by side.
       */}
      <div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2">
        <div className={surfaceClass} style={metricCardStyle} data-testid="pv-swing-track">
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            {SUBHEADING_SWING_CADENCE}
          </p>
          <p className="mt-2 text-2xl font-bold" style={{ fontFamily: typography.fontFamilyMono }}>
            {swing ? formatAccuracyPercent(swing.accuracy) : "—"}
          </p>
          <p className="mt-1 text-[11px] leading-snug" style={{ color: colors.textMuted }}>
            {swing && swing.correct + swing.incorrect > 0
              ? `${swing.correct} correct of ${swing.correct + swing.incorrect} resolved`
              : "Awaiting resolved swing signals"}
          </p>
        </div>

        <div className={surfaceClass} style={metricCardStyle} data-testid="pv-day-track">
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            {SUBHEADING_DAY_CADENCE}
          </p>
          <p className="mt-2 text-2xl font-bold" style={{ fontFamily: typography.fontFamilyMono }}>
            {day ? formatAccuracyPercent(day.accuracy) : "—"}
          </p>
          <p className="mt-1 text-[11px] leading-snug" style={{ color: colors.textMuted }}>
            {day && day.correct + day.incorrect > 0
              ? `${day.correct} correct of ${day.correct + day.incorrect} resolved`
              : "Awaiting resolved day signals"}
          </p>
        </div>
      </div>

      <p className="mt-4 text-xs" style={{ color: colors.textMuted, fontStyle: "italic", lineHeight: 1.6 }}>
        Based on {rowsExamined} signal{rowsExamined === 1 ? "" : "s"} examined.{" "}
        {/*
         * The standing disclaimer is rendered verbatim from the backend response so the
         * exact wording is single-sourced across the assistant prompt, the API, and the
         * UI. If the backend wording changes, this surface picks it up automatically.
         */}
        {validation.disclaimer}
      </p>

      <p className="mt-3 text-xs" style={{ color: colors.textMuted }}>
        Sign in to see the full stratified breakdown — decision state, regime, setup pattern, readiness, and direction
        — for your own tracked outcomes.
      </p>
    </section>
  );
}
