"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import {
  fetchLiveSignals,
  fetchPerformanceSummary,
  formatHorizonOutcome,
  type PerformanceSummary,
  type PublicSignal
} from "@/lib/api/public-signals";
import { usePublishAssistantContext } from "@/lib/assistant/context";
import { borderRadius, spacing, surfaceGlowClassName, typography } from "@/lib/design-system";
import { isoDateInNewYork } from "@/lib/market-hours-et";
import { useTheme } from "@/lib/theme-provider";

function outcomeLabel(outcome: PublicSignal["outcome"]): string {
  if (outcome === "correct") return "Price moved in signal direction";
  if (outcome === "incorrect") return "Price moved against signal direction";
  if (outcome === "neutral") return "Price drifted (no clear move)";
  return "Pending evaluation";
}

interface PerformanceTrackingContentProps {
  showHomeLink?: boolean;
}

export function PerformanceTrackingContent({ showHomeLink = false }: PerformanceTrackingContentProps) {
  const { colors } = useTheme();
  const [signals, setSignals] = useState<PublicSignal[]>([]);
  const [summary, setSummary] = useState<PerformanceSummary | null>(null);

  usePublishAssistantContext({ page: "dashboard/performance" });

  useEffect(() => {
    let active = true;
    const load = async () => {
      const [s, p] = await Promise.all([fetchLiveSignals(), fetchPerformanceSummary()]);
      if (!active) return;
      setSignals(s);
      setSummary(p);
    };
    void load();
    return () => {
      active = false;
    };
  }, []);

  const launchDate = summary?.launch_date ?? isoDateInNewYork();
  const resolvedCount = summary?.signals_evaluated ?? 0;
  const showTable = signals.length > 0;

  const metricCardStyle = {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: borderRadius.xl,
    padding: spacing[4]
  } as const;

  const bodyPanelStyle = {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: borderRadius.xl,
    padding: spacing[6]
  } as const;

  return (
    <div className="overflow-x-hidden" style={{ color: colors.text }}>
      {showHomeLink ? (
        <Link href="/" className="text-sm hover:underline" style={{ color: colors.accent }}>
          ← Back to home
        </Link>
      ) : null}
      <h1 className={`font-black ${showHomeLink ? "mt-5 text-4xl md:text-6xl" : "text-2xl md:text-3xl"}`}>
        Signal outcome tracking
      </h1>
      <p className={`max-w-4xl ${showHomeLink ? "mt-3 md:text-xl" : "mt-2 text-sm md:text-base"}`} style={{ color: colors.textMuted }}>
        Every signal generated by STOCVEST is tracked against subsequent market price movement. Directional accuracy reflects signal
        direction only — not trading returns. Individual results will vary based on entry timing, position size, and execution. Historical
        signal accuracy does not guarantee future results.
      </p>

      <section
        className={`grid grid-cols-1 gap-3 sm:grid-cols-2 ${showHomeLink ? "mt-8 lg:grid-cols-4" : "mt-6 lg:grid-cols-4"}`}
      >
        <div className={surfaceGlowClassName} style={metricCardStyle}>
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            Total Signals
          </p>
          <p className="mt-2 text-2xl font-bold">{summary?.total_signals_tracked ?? 0}</p>
        </div>
        <div className={surfaceGlowClassName} style={metricCardStyle}>
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            Directional Accuracy
          </p>
          <p className="mt-2 text-2xl font-bold">
            {summary && summary.correct_direction_count + summary.incorrect_direction_count > 0
              ? `${summary.directional_accuracy_percent.toFixed(1)}%`
              : "—"}
          </p>
        </div>
        <div className={surfaceGlowClassName} style={metricCardStyle}>
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            Signals Evaluated
          </p>
          <p className="mt-2 text-2xl font-bold">{resolvedCount}</p>
        </div>
        <div className={surfaceGlowClassName} style={metricCardStyle}>
          <p className="text-xs uppercase tracking-wide" style={{ color: colors.textMuted }}>
            Tracking Since
          </p>
          <p className="mt-2 text-2xl font-bold">{launchDate}</p>
          <p className="mt-1 text-[11px] leading-snug" style={{ color: colors.textMuted }}>
            US/Eastern market calendar
          </p>
        </div>
      </section>

      {resolvedCount > 0 ? (
        <p className="mt-4 text-sm" style={{ color: colors.textMuted }}>
          Based on {resolvedCount} resolved signal{resolvedCount === 1 ? "" : "s"} since launch (1d horizon). Pending signals are excluded
          from the accuracy percentage.
        </p>
      ) : null}

      {!showTable ? (
        <section className={`${surfaceGlowClassName} ${showHomeLink ? "mt-8" : "mt-6"}`} style={bodyPanelStyle}>
          <h2 className="text-2xl font-bold">Accuracy Tracking Starts Now</h2>
          <p className="mt-3" style={{ color: colors.textMuted }}>
            We launched on {launchDate} (US/Eastern). Signal accuracy data accumulates as composite signals are recorded with
            symbol and price.
            <br />
            Every signal is evaluated for directional accuracy only (not dollar P&amp;L).
            <br />
            Check back after market hours once signals have been generated and resolved.
          </p>
          {showHomeLink ? (
            <Link
              href="/#live-signals"
              className="mt-5 inline-block rounded-md px-4 py-2 text-sm"
              style={{
                border: `1px solid ${colors.border}`,
                color: colors.accent
              }}
            >
              View Live Signals
            </Link>
          ) : null}
        </section>
      ) : (
        <section
          className={`overflow-x-auto overscroll-x-contain touch-pan-x ${surfaceGlowClassName} ${showHomeLink ? "mt-8" : "mt-6"}`}
          style={{
            background: colors.surface,
            border: `1px solid ${colors.border}`,
            borderRadius: borderRadius.xl,
            padding: spacing[3]
          }}
        >
          <table className="w-full min-w-[900px] text-sm" style={{ borderCollapse: "collapse", fontSize: typography.scale.sm }}>
            <thead>
              <tr className="text-left" style={{ borderBottom: `1px solid ${colors.border}`, color: colors.textMuted }}>
                <th className="px-4 py-3">Symbol</th>
                <th className="px-4 py-3">Direction</th>
                <th className="px-4 py-3">Signal Strength</th>
                <th className="px-4 py-3">Date and Time</th>
                <th className="px-4 py-3">1h</th>
                <th className="px-4 py-3">1d</th>
                <th className="px-4 py-3">Legacy</th>
              </tr>
            </thead>
            <tbody>
              {signals.map((row) => {
                const h1 = formatHorizonOutcome(row.outcome_1h);
                const h1d = formatHorizonOutcome(row.outcome_1d);
                return (
                  <tr key={row.signal_id ?? `${row.symbol}-${row.timestamp_iso}`} style={{ borderBottom: `1px solid ${colors.border}` }}>
                    <td className="px-4 py-3 font-semibold">{row.symbol}</td>
                    <td className="px-4 py-3 capitalize">{row.bias}</td>
                    <td className="px-4 py-3">{Math.round(row.signal_strength)}%</td>
                    <td className="px-4 py-3" style={{ color: colors.textMuted }}>
                      {new Date(row.timestamp_iso).toLocaleString()}
                    </td>
                    <td className="px-4 py-3" style={{ color: colors.textMuted }}>
                      {h1.label}
                    </td>
                    <td className="px-4 py-3" style={{ color: colors.textMuted }}>
                      {h1d.label}
                    </td>
                    <td className="px-4 py-3">{outcomeLabel(row.outcome)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>
      )}

      <section className={`${surfaceGlowClassName} ${showHomeLink ? "mt-8" : "mt-6"}`} style={bodyPanelStyle}>
        <h2 className="text-2xl font-bold">Our commitment to transparency</h2>
        <ul className="mt-3 list-disc space-y-1 pl-6" style={{ color: colors.textMuted }}>
          <li>We publish signal outcomes — not only directionally correct results</li>
          <li>Small sample sizes are shown with sample count</li>
          <li>Past signal accuracy does not guarantee future results</li>
          <li>Directional accuracy uses resolved 1d outcomes; correct ÷ (correct + incorrect), excluding neutral moves</li>
          <li>Moves within 0.1% are scored as neutral</li>
        </ul>
      </section>
    </div>
  );
}
