"""Default sector bucket → benchmark ETF mapping (tunable via SignalParameters.sector_to_etf)."""

from __future__ import annotations

DEFAULT_SECTOR_TO_ETF: dict[str, str] = {
    "semiconductors": "SOXX",
    "software": "IGV",
    "hardware": "XLK",
    "internet": "XLK",
    "technology": "XLK",
    "banks": "KBE",
    "investment_services": "XLF",
    "insurance": "XLF",
    "consumer_finance": "XLF",
    "financials": "XLF",
    "pharma": "XPH",
    "biotech": "XBI",
    "medical_devices": "IHI",
    "health_services": "XLV",
    "healthcare": "XLV",
    "auto": "XLY",
    "retail": "XRT",
    "restaurants": "XLY",
    "consumer_disc": "XLY",
    "food_beverage": "XLP",
    "consumer_staples": "XLP",
    "oil_gas": "XLE",
    "energy": "XLE",
    "airlines": "JETS",
    "transport": "XTN",
    "industrials": "XLI",
    "aerospace_defense": "ITA",
    "telecom": "XLC",
    "media": "XLC",
    "communication": "XLC",
    "real_estate": "XLRE",
    "utilities": "XLU",
    "mining": "XME",
    "materials": "XLB",
    "chemicals": "XLB",
    "metals": "XLB",
    "default": "SPY",
}
