"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { fetchLiveSignals, fetchPerformanceSummary, type PerformanceSummary, type PublicSignal } from "@/lib/api/public-signals";

function outcomeLabel(outcome: PublicSignal["outcome"]): string {
  if (outcome === "win") return "✅ Direction correct";
  if (outcome === "loss") return "❌ Direction incorrect";
  if (outcome === "neutral") return "➖ Neutral";
  return "⏳ Pending";
}

export default function PerformancePage() {
  const [signals, setSignals] = useState<PublicSignal[]>([]);
  const [summary, setSummary] = useState<PerformanceSummary | null>(null);

  useEffect(() => {
    let active = true;
    const load = async () => {
      const [s, p] = await Promise.all([fetchLiveSignals(), fetchPerformanceSummary()]);
      if (!active) return;
      setSignals(s.slice(0, 20));
      setSummary(p);
    };
    void load();
    return () => {
      active = false;
    };
  }, []);

  const launchDate = summary?.launch_date ?? new Date().toISOString().slice(0, 10);

  return (
    <main className="min-h-screen overflow-x-hidden bg-[#0a0e1a] px-4 py-14 text-slate-100 md:px-8">
      <div className="mx-auto max-w-7xl">
        <Link href="/" className="text-sm text-[#3b82f6] hover:underline">
          ← Back to home
        </Link>
        <h1 className="mt-5 text-4xl font-black md:text-6xl">Signal Accuracy Tracking</h1>
        <p className="mt-3 max-w-4xl text-slate-300 md:text-xl">
          Every signal generated by STOCVEST is tracked against subsequent market price movement. Directional accuracy reflects signal
          direction only — not trading returns. Individual results will vary based on entry timing, position size, and execution. Historical
          signal accuracy does not guarantee future results.
        </p>

        <section className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs uppercase tracking-wide text-slate-400">Total Signals</p>
            <p className="mt-2 text-2xl font-bold">{summary?.total_signals_tracked ?? 0}</p>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs uppercase tracking-wide text-slate-400">Directional Accuracy</p>
            <p className="mt-2 text-2xl font-bold">
              {summary ? `${summary.directional_accuracy_percent.toFixed(1)}%` : "—"}
            </p>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs uppercase tracking-wide text-slate-400">Signals Evaluated</p>
            <p className="mt-2 text-2xl font-bold">{summary?.signals_evaluated ?? 0}</p>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <p className="text-xs uppercase tracking-wide text-slate-400">Tracking Since</p>
            <p className="mt-2 text-2xl font-bold">{launchDate}</p>
          </div>
        </section>

        {signals.length === 0 ? (
          <section className="mt-8 rounded-xl border border-white/10 bg-white/5 p-6">
            <h2 className="text-2xl font-bold">Accuracy Tracking Starts Now</h2>
            <p className="mt-3 text-slate-300">
              We launched on {launchDate}. Signal accuracy data accumulates from our first day.
              <br />
              Every signal generated from this point is evaluated for directional accuracy only (not dollar P&amp;L).
              <br />
              Check back in 7 days for our first week of accuracy data.
            </p>
            <Link href="/#live-signals" className="mt-5 inline-block rounded-md border border-white/20 px-4 py-2 text-sm hover:border-white/40">
              View Live Signals
            </Link>
          </section>
        ) : (
          <section className="mt-8 overflow-x-auto rounded-xl border border-white/10">
            <table className="w-full min-w-[720px] bg-white/5 text-sm">
              <thead>
                <tr className="border-b border-white/10 text-left text-slate-300">
                  <th className="px-4 py-3">Symbol</th>
                  <th className="px-4 py-3">Direction</th>
                  <th className="px-4 py-3">Signal Strength</th>
                  <th className="px-4 py-3">Date and Time</th>
                  <th className="px-4 py-3">Outcome</th>
                </tr>
              </thead>
              <tbody>
                {signals.map((row) => (
                  <tr key={`${row.symbol}-${row.timestamp_iso}`} className="border-b border-white/10">
                    <td className="px-4 py-3 font-semibold">{row.symbol}</td>
                    <td className="px-4 py-3 capitalize">{row.direction}</td>
                    <td className="px-4 py-3">{Math.round(row.signal_strength)}%</td>
                    <td className="px-4 py-3 text-slate-300">{new Date(row.timestamp_iso).toLocaleString()}</td>
                    <td className="px-4 py-3">{outcomeLabel(row.outcome)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        <section className="mt-8 rounded-xl border border-white/10 bg-white/5 p-6">
          <h2 className="text-2xl font-bold">Our commitment to transparency</h2>
          <ul className="mt-3 list-disc space-y-1 pl-6 text-slate-300">
            <li>We publish every signal — not just directionally correct outcomes</li>
            <li>Small sample sizes are shown with sample count</li>
            <li>Past signal accuracy does not guarantee future results</li>
            <li>Directional accuracy is calculated on evaluated signals only</li>
            <li>A signal is evaluated when price moves more than 0.5% within 24 hours</li>
          </ul>
        </section>
      </div>
    </main>
  );
}
